// Data types and constants for Peakly

export interface Tool {
  id: string;
  name: string;
  category: string;
  description: string;
  trending: boolean;
  trendingScore: number; // 0-100
  signalType: 'breakthrough' | 'rising' | 'declining' | 'stable';
  newsCount: number;
  metrics: {
    monthlyGrowth: number; // percentage
    userSentiment: number; // 0-100
    adoptionRate: number; // 0-100
  };
  icon?: string;
  website?: string;
}

export interface NewsItem {
  id: string;
  title: string;
  source: string;
  date: string;
  toolId: string;
  sentiment: 'positive' | 'neutral' | 'negative';
  summary: string;
}

// 50+ AI Tools Database
export const tools: Tool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'Language Model',
    description: 'Advanced conversational AI from OpenAI',
    trending: true,
    trendingScore: 95,
    signalType: 'breakthrough',
    newsCount: 42,
    metrics: { monthlyGrowth: 23, userSentiment: 88, adoptionRate: 92 },
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'Language Model',
    description: 'Constitutional AI assistant by Anthropic',
    trending: true,
    trendingScore: 88,
    signalType: 'breakthrough',
    newsCount: 38,
    metrics: { monthlyGrowth: 31, userSentiment: 91, adoptionRate: 85 },
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'Language Model',
    description: 'Google\'s multimodal AI model',
    trending: true,
    trendingScore: 82,
    signalType: 'rising',
    newsCount: 35,
    metrics: { monthlyGrowth: 18, userSentiment: 79, adoptionRate: 78 },
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    category: 'Code Generation',
    description: 'AI-powered coding assistant',
    trending: true,
    trendingScore: 85,
    signalType: 'rising',
    newsCount: 32,
    metrics: { monthlyGrowth: 25, userSentiment: 83, adoptionRate: 81 },
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'Image Generation',
    description: 'AI image synthesis platform',
    trending: true,
    trendingScore: 78,
    signalType: 'stable',
    newsCount: 28,
    metrics: { monthlyGrowth: 12, userSentiment: 82, adoptionRate: 75 },
  },
  {
    id: 'dall-e',
    name: 'DALL-E',
    category: 'Image Generation',
    description: 'Text-to-image generation by OpenAI',
    trending: true,
    trendingScore: 75,
    signalType: 'stable',
    newsCount: 26,
    metrics: { monthlyGrowth: 8, userSentiment: 80, adoptionRate: 72 },
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    category: 'Image Generation',
    description: 'Open-source image generation model',
    trending: false,
    trendingScore: 62,
    signalType: 'declining',
    newsCount: 18,
    metrics: { monthlyGrowth: -5, userSentiment: 76, adoptionRate: 68 },
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'Search & Research',
    description: 'AI-powered research and discovery engine',
    trending: true,
    trendingScore: 72,
    signalType: 'rising',
    newsCount: 24,
    metrics: { monthlyGrowth: 29, userSentiment: 81, adoptionRate: 70 },
  },
  {
    id: 'notionai',
    name: 'Notion AI',
    category: 'Productivity',
    description: 'AI features integrated into Notion',
    trending: false,
    trendingScore: 58,
    signalType: 'stable',
    newsCount: 14,
    metrics: { monthlyGrowth: 3, userSentiment: 77, adoptionRate: 65 },
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'Code Generation',
    description: 'AI-first code editor',
    trending: true,
    trendingScore: 80,
    signalType: 'breakthrough',
    newsCount: 30,
    metrics: { monthlyGrowth: 35, userSentiment: 89, adoptionRate: 79 },
  },
  {
    id: 'v0',
    name: 'v0',
    category: 'UI Generation',
    description: 'AI-powered UI component generator',
    trending: true,
    trendingScore: 77,
    signalType: 'rising',
    newsCount: 22,
    metrics: { monthlyGrowth: 28, userSentiment: 86, adoptionRate: 74 },
  },
  {
    id: 'eleven-labs',
    name: 'Eleven Labs',
    category: 'Audio/Voice',
    description: 'AI voice synthesis and generation',
    trending: true,
    trendingScore: 70,
    signalType: 'rising',
    newsCount: 20,
    metrics: { monthlyGrowth: 22, userSentiment: 84, adoptionRate: 71 },
  },
  {
    id: 'dify',
    name: 'Dify',
    category: 'LLM Ops',
    description: 'Open-source LLM application framework',
    trending: false,
    trendingScore: 55,
    signalType: 'rising',
    newsCount: 12,
    metrics: { monthlyGrowth: 15, userSentiment: 78, adoptionRate: 60 },
  },
  {
    id: 'retool',
    name: 'Retool',
    category: 'Internal Tools',
    description: 'Low-code platform for building internal tools',
    trending: false,
    trendingScore: 52,
    signalType: 'stable',
    newsCount: 10,
    metrics: { monthlyGrowth: 2, userSentiment: 80, adoptionRate: 62 },
  },
  {
    id: 'make',
    name: 'Make',
    category: 'Automation',
    description: 'Visual automation platform',
    trending: false,
    trendingScore: 50,
    signalType: 'stable',
    newsCount: 8,
    metrics: { monthlyGrowth: -1, userSentiment: 79, adoptionRate: 61 },
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'Automation',
    description: 'Connect and automate your apps',
    trending: false,
    trendingScore: 48,
    signalType: 'stable',
    newsCount: 7,
    metrics: { monthlyGrowth: 0, userSentiment: 78, adoptionRate: 59 },
  },
  {
    id: 'langchain',
    name: 'LangChain',
    category: 'Developer Tools',
    description: 'Framework for building LLM applications',
    trending: true,
    trendingScore: 68,
    signalType: 'rising',
    newsCount: 25,
    metrics: { monthlyGrowth: 26, userSentiment: 82, adoptionRate: 73 },
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'ML Platform',
    description: 'Open-source ML models and datasets',
    trending: true,
    trendingScore: 71,
    signalType: 'rising',
    newsCount: 27,
    metrics: { monthlyGrowth: 19, userSentiment: 85, adoptionRate: 76 },
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'ML API',
    description: 'Run open-source ML models in the cloud',
    trending: false,
    trendingScore: 54,
    signalType: 'stable',
    newsCount: 11,
    metrics: { monthlyGrowth: 5, userSentiment: 80, adoptionRate: 64 },
  },
  {
    id: 'vercel-ai',
    name: 'Vercel AI SDK',
    category: 'Developer Tools',
    description: 'JavaScript SDK for AI development',
    trending: true,
    trendingScore: 73,
    signalType: 'rising',
    newsCount: 19,
    metrics: { monthlyGrowth: 24, userSentiment: 87, adoptionRate: 72 },
  },
  {
    id: 'anthropic-api',
    name: 'Anthropic API',
    category: 'API',
    description: 'Claude API for developers',
    trending: true,
    trendingScore: 79,
    signalType: 'rising',
    newsCount: 23,
    metrics: { monthlyGrowth: 27, userSentiment: 88, adoptionRate: 77 },
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'Inference',
    description: 'Ultra-fast LLM inference',
    trending: true,
    trendingScore: 74,
    signalType: 'breakthrough',
    newsCount: 21,
    metrics: { monthlyGrowth: 34, userSentiment: 86, adoptionRate: 75 },
  },
  {
    id: 'together-ai',
    name: 'Together AI',
    category: 'Inference',
    description: 'Open-source model inference platform',
    trending: false,
    trendingScore: 56,
    signalType: 'rising',
    newsCount: 13,
    metrics: { monthlyGrowth: 18, userSentiment: 81, adoptionRate: 63 },
  },
  {
    id: 'modal',
    name: 'Modal',
    category: 'Cloud',
    description: 'Serverless cloud platform for ML',
    trending: false,
    trendingScore: 51,
    signalType: 'stable',
    newsCount: 9,
    metrics: { monthlyGrowth: 4, userSentiment: 79, adoptionRate: 60 },
  },
  {
    id: 'runwayml',
    name: 'Runway',
    category: 'Video/Creative',
    description: 'AI video generation and editing',
    trending: true,
    trendingScore: 69,
    signalType: 'rising',
    newsCount: 20,
    metrics: { monthlyGrowth: 21, userSentiment: 83, adoptionRate: 70 },
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    category: 'Video/Creative',
    description: 'AI video creation platform',
    trending: false,
    trendingScore: 57,
    signalType: 'stable',
    newsCount: 12,
    metrics: { monthlyGrowth: 6, userSentiment: 81, adoptionRate: 64 },
  },
  {
    id: 'descript',
    name: 'Descript',
    category: 'Audio/Video',
    description: 'AI-powered audio and video editing',
    trending: false,
    trendingScore: 59,
    signalType: 'stable',
    newsCount: 13,
    metrics: { monthlyGrowth: 7, userSentiment: 82, adoptionRate: 66 },
  },
  {
    id: 'jasper',
    name: 'Jasper',
    category: 'Content',
    description: 'AI content creation and copywriting',
    trending: false,
    trendingScore: 53,
    signalType: 'declining',
    newsCount: 10,
    metrics: { monthlyGrowth: -3, userSentiment: 76, adoptionRate: 61 },
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    category: 'Content',
    description: 'AI copywriting assistant',
    trending: false,
    trendingScore: 49,
    signalType: 'declining',
    newsCount: 6,
    metrics: { monthlyGrowth: -4, userSentiment: 74, adoptionRate: 58 },
  },
  {
    id: 'pictory',
    name: 'Pictory',
    category: 'Video',
    description: 'AI video creation from text',
    trending: false,
    trendingScore: 47,
    signalType: 'declining',
    newsCount: 5,
    metrics: { monthlyGrowth: -6, userSentiment: 72, adoptionRate: 55 },
  },
  {
    id: 'murf-ai',
    name: 'Murf AI',
    category: 'Voice',
    description: 'Text-to-speech voice generation',
    trending: false,
    trendingScore: 52,
    signalType: 'stable',
    newsCount: 9,
    metrics: { monthlyGrowth: 3, userSentiment: 79, adoptionRate: 61 },
  },
  {
    id: 'article-ai',
    name: 'Article.ai',
    category: 'Writing',
    description: 'Long-form AI content generation',
    trending: false,
    trendingScore: 44,
    signalType: 'declining',
    newsCount: 4,
    metrics: { monthlyGrowth: -8, userSentiment: 70, adoptionRate: 52 },
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    category: 'Writing',
    description: 'AI writing assistant and editor',
    trending: false,
    trendingScore: 50,
    signalType: 'stable',
    newsCount: 8,
    metrics: { monthlyGrowth: 2, userSentiment: 78, adoptionRate: 60 },
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    category: 'Writing',
    description: 'AI grammar and writing assistant',
    trending: false,
    trendingScore: 46,
    signalType: 'stable',
    newsCount: 7,
    metrics: { monthlyGrowth: 1, userSentiment: 77, adoptionRate: 58 },
  },
  {
    id: 'deepl',
    name: 'DeepL',
    category: 'Translation',
    description: 'AI-powered translation',
    trending: false,
    trendingScore: 51,
    signalType: 'stable',
    newsCount: 9,
    metrics: { monthlyGrowth: 4, userSentiment: 80, adoptionRate: 62 },
  },
  {
    id: 'uberduck',
    name: 'Uberduck',
    category: 'Audio',
    description: 'AI voice cloning and synthesis',
    trending: false,
    trendingScore: 48,
    signalType: 'stable',
    newsCount: 7,
    metrics: { monthlyGrowth: 2, userSentiment: 76, adoptionRate: 59 },
  },
  {
    id: 'openjourney',
    name: 'OpenJourney',
    category: 'Image',
    description: 'Open-source image generation model',
    trending: false,
    trendingScore: 40,
    signalType: 'declining',
    newsCount: 3,
    metrics: { monthlyGrowth: -9, userSentiment: 68, adoptionRate: 50 },
  },
  {
    id: 'animatediff',
    name: 'AnimateDiff',
    category: 'Video',
    description: 'Text-to-video animation generation',
    trending: true,
    trendingScore: 65,
    signalType: 'rising',
    newsCount: 16,
    metrics: { monthlyGrowth: 20, userSentiment: 81, adoptionRate: 68 },
  },
  {
    id: 'pika',
    name: 'Pika',
    category: 'Video',
    description: 'AI video generation from text',
    trending: true,
    trendingScore: 76,
    signalType: 'breakthrough',
    newsCount: 25,
    metrics: { monthlyGrowth: 32, userSentiment: 85, adoptionRate: 76 },
  },
  {
    id: 'lumiere',
    name: 'Lumiere (Google)',
    category: 'Video',
    description: 'Google\'s text-to-video model',
    trending: true,
    trendingScore: 81,
    signalType: 'breakthrough',
    newsCount: 29,
    metrics: { monthlyGrowth: 33, userSentiment: 87, adoptionRate: 80 },
  },
  {
    id: 'suno',
    name: 'Suno',
    category: 'Music',
    description: 'AI music generation from text',
    trending: true,
    trendingScore: 72,
    signalType: 'breakthrough',
    newsCount: 24,
    metrics: { monthlyGrowth: 30, userSentiment: 84, adoptionRate: 73 },
  },
  {
    id: 'udio',
    name: 'Udio',
    category: 'Music',
    description: 'AI music creation assistant',
    trending: true,
    trendingScore: 70,
    signalType: 'rising',
    newsCount: 19,
    metrics: { monthlyGrowth: 26, userSentiment: 83, adoptionRate: 71 },
  },
  {
    id: 'musicfy',
    name: 'Musicfy',
    category: 'Music',
    description: 'AI voice cloning for music',
    trending: false,
    trendingScore: 54,
    signalType: 'stable',
    newsCount: 10,
    metrics: { monthlyGrowth: 5, userSentiment: 78, adoptionRate: 62 },
  },
  {
    id: 'elevenlabs-premium',
    name: 'Eleven Labs Premium',
    category: 'Voice',
    description: 'Premium voice synthesis',
    trending: false,
    trendingScore: 60,
    signalType: 'stable',
    newsCount: 14,
    metrics: { monthlyGrowth: 8, userSentiment: 82, adoptionRate: 67 },
  },
  {
    id: 'whisper',
    name: 'Whisper (OpenAI)',
    category: 'Speech-to-Text',
    description: 'Open-source speech recognition',
    trending: false,
    trendingScore: 63,
    signalType: 'stable',
    newsCount: 15,
    metrics: { monthlyGrowth: 10, userSentiment: 83, adoptionRate: 69 },
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'API',
    description: 'Enterprise NLP API',
    trending: false,
    trendingScore: 55,
    signalType: 'stable',
    newsCount: 11,
    metrics: { monthlyGrowth: 6, userSentiment: 79, adoptionRate: 63 },
  },
  {
    id: 'ai21-labs',
    name: 'AI21 Labs',
    category: 'API',
    description: 'Large language model APIs',
    trending: false,
    trendingScore: 49,
    signalType: 'stable',
    newsCount: 8,
    metrics: { monthlyGrowth: 3, userSentiment: 77, adoptionRate: 59 },
  },
  {
    id: 'llamaindex',
    name: 'LlamaIndex',
    category: 'Developer Tools',
    description: 'Data framework for LLM apps',
    trending: true,
    trendingScore: 67,
    signalType: 'rising',
    newsCount: 18,
    metrics: { monthlyGrowth: 23, userSentiment: 84, adoptionRate: 71 },
  },
  {
    id: 'mem0',
    name: 'Mem0',
    category: 'Developer Tools',
    description: 'Memory layer for AI apps',
    trending: true,
    trendingScore: 66,
    signalType: 'rising',
    newsCount: 17,
    metrics: { monthlyGrowth: 22, userSentiment: 83, adoptionRate: 70 },
  },
];

// Sample News Items
export const news: NewsItem[] = [
  {
    id: 'news-001',
    title: 'Claude 3.5 Sonnet Launches with Revolutionary Context Window',
    source: 'TechCrunch',
    date: '2024-04-20',
    toolId: 'claude',
    sentiment: 'positive',
    summary: 'Anthropic announces Claude 3.5 Sonnet with 200K context window and improved reasoning capabilities.',
  },
  {
    id: 'news-002',
    title: 'ChatGPT Surpasses 100M Weekly Active Users',
    source: 'OpenAI Blog',
    date: '2024-04-19',
    toolId: 'chatgpt',
    sentiment: 'positive',
    summary: 'OpenAI reports ChatGPT has reached over 100 million weekly active users.',
  },
  {
    id: 'news-003',
    title: 'Cursor IDE Raises Series B Funding at $60M Valuation',
    source: 'VentureBeat',
    date: '2024-04-18',
    toolId: 'cursor',
    sentiment: 'positive',
    summary: 'Cursor, the AI-first code editor, secures Series B funding and hits $60M valuation.',
  },
  {
    id: 'news-004',
    title: 'Gemini 1.5 Pro Now Available with 2M Token Context',
    source: 'Google AI Blog',
    date: '2024-04-17',
    toolId: 'gemini',
    sentiment: 'positive',
    summary: 'Google releases Gemini 1.5 Pro supporting 2 million tokens context window.',
  },
  {
    id: 'news-005',
    title: 'Pika AI Raises $80M Series A for Text-to-Video',
    source: 'Crunchbase',
    date: '2024-04-16',
    toolId: 'pika',
    sentiment: 'positive',
    summary: 'Pika AI secures $80M Series A funding to accelerate video generation capabilities.',
  },
  {
    id: 'news-006',
    title: 'Groq Announces Fastest LLM Inference Engine',
    source: 'Groq Press Release',
    date: '2024-04-15',
    toolId: 'groq',
    sentiment: 'positive',
    summary: 'Groq releases updated inference engine delivering 3x faster LLM processing.',
  },
  {
    id: 'news-007',
    title: 'Suno V3 Music Generation Model Released',
    source: 'Suno Blog',
    date: '2024-04-14',
    toolId: 'suno',
    sentiment: 'positive',
    summary: 'Suno launches V3 with improved music quality and longer track generation.',
  },
  {
    id: 'news-008',
    title: 'LangChain Releases LangSmith Monitoring Platform',
    source: 'LangChain News',
    date: '2024-04-13',
    toolId: 'langchain',
    sentiment: 'positive',
    summary: 'LangChain introduces LangSmith for comprehensive LLM app monitoring.',
  },
  {
    id: 'news-009',
    title: 'Hugging Face Reaches 1 Million Models',
    source: 'Hugging Face Blog',
    date: '2024-04-12',
    toolId: 'huggingface',
    sentiment: 'positive',
    summary: 'Hugging Face community reaches milestone of 1 million open-source models.',
  },
  {
    id: 'news-010',
    title: 'Lumiere: Google\'s Revolutionary Video Generation Model',
    source: 'Google Blog',
    date: '2024-04-11',
    toolId: 'lumiere',
    sentiment: 'positive',
    summary: 'Google introduces Lumiere, a breakthrough text-to-video generation model.',
  },
];

// Category colors for visualization
export const categoryColors: Record<string, string> = {
  'Language Model': '#65B741',
  'Code Generation': '#3B82F6',
  'Image Generation': '#F59E0B',
  'Search & Research': '#8B5CF6',
  'Productivity': '#EC4899',
  'Audio/Voice': '#10B981',
  'LLM Ops': '#F97316',
  'Internal Tools': '#06B6D4',
  'Automation': '#6366F1',
  'Developer Tools': '#3B82F6',
  'ML Platform': '#8B5CF6',
  'ML API': '#5B21B6',
  'API': '#D946EF',
  'Inference': '#DC2626',
  'Cloud': '#16A34A',
  'Video/Creative': '#E91E63',
  'Video': '#9C27B0',
  'Content': '#FF7043',
  'Writing': '#4DB6AC',
  'Translation': '#9CCC65',
  'Voice': '#00BCD4',
  'Image': '#FFB74D',
  'Music': '#AB47BC',
  'Speech-to-Text': '#7986CB',
};
