export type ToolCategory =
  | 'AI Writing'
  | 'AI Image'
  | 'Productivity'
  | 'Developer Tools'
  | 'Marketing'
  | 'Analytics'
  | 'Design'
  | 'Customer Support'
  | 'Finance'
  | 'HR';

export type ToolPricing = 'free' | 'freemium' | 'paid';
export type ToolStatus = 'hot' | 'rising' | 'stable' | 'declining';

export interface ToolData {
  id: string;
  name: string;
  website: string;
  category: ToolCategory;
  description: string;
  pricing: ToolPricing;
  launched: number;
  trendScore: number;
  weeklyGrowth: number;
  monthlyVisits: number;
  tags: string[];
  status: ToolStatus;
  ph_slug?: string;
  github_repo?: string;
  npm_package?: string;
  youtube_query?: string;
  reddit_query?: string;
}

export const toolsData: ToolData[] = [
  {
    id: 'notion',
    name: 'Notion',
    website: 'https://www.notion.so',
    github_repo: 'makenotion/notion-sdk-js',
    category: 'Productivity',
    description: 'All-in-one workspace for docs, wikis, and project planning.',
    pricing: 'freemium',
    launched: 2016,
    trendScore: 84,
    weeklyGrowth: 3.2,
    monthlyVisits: 185000000,
    tags: ['workspace', 'notes', 'collaboration'],
    status: 'stable',
  },
  {
    id: 'linear',
    name: 'Linear',
    website: 'https://linear.app',
    github_repo: 'linear/linear',
    category: 'Productivity',
    description: 'Issue tracking and product management platform for modern teams.',
    pricing: 'freemium',
    launched: 2019,
    trendScore: 88,
    weeklyGrowth: 6.1,
    monthlyVisits: 9800000,
    tags: ['project-management', 'issues', 'product'],
    status: 'rising',
  },
  {
    id: 'figma',
    name: 'Figma',
    website: 'https://www.figma.com',
    github_repo: 'figma/plugin-samples',
    category: 'Design',
    description: 'Cloud design tool for interface design and team collaboration.',
    pricing: 'freemium',
    launched: 2016,
    trendScore: 90,
    weeklyGrowth: 4.4,
    monthlyVisits: 102000000,
    tags: ['ui', 'ux', 'collaboration'],
    status: 'hot',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    website: 'https://vercel.com',
    github_repo: 'vercel/vercel',
    category: 'Developer Tools',
    description: 'Deployment and edge platform optimized for frontend frameworks.',
    pricing: 'freemium',
    launched: 2015,
    trendScore: 92,
    weeklyGrowth: 7.3,
    monthlyVisits: 21000000,
    tags: ['hosting', 'frontend', 'serverless'],
    status: 'hot',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    website: 'https://supabase.com',
    github_repo: 'supabase/supabase',
    category: 'Developer Tools',
    description: 'Open-source backend platform with Postgres, auth, and storage.',
    pricing: 'freemium',
    launched: 2020,
    trendScore: 93,
    weeklyGrowth: 8.5,
    monthlyVisits: 17000000,
    tags: ['database', 'auth', 'backend'],
    status: 'hot',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    website: 'https://openai.com',
    github_repo: 'openai/openai-python',
    category: 'AI Writing',
    description: 'Leading AI platform for text generation, assistants, and APIs.',
    pricing: 'paid',
    launched: 2015,
    trendScore: 97,
    weeklyGrowth: 9.2,
    monthlyVisits: 320000000,
    tags: ['llm', 'api', 'chatbot'],
    status: 'hot',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    website: 'https://www.midjourney.com',
    github_repo: 'midjourney/docs',
    category: 'AI Image',
    description: 'AI image generation service known for high-quality artistic outputs.',
    pricing: 'paid',
    launched: 2022,
    trendScore: 91,
    weeklyGrowth: 5.7,
    monthlyVisits: 16500000,
    tags: ['text-to-image', 'art', 'creative'],
    status: 'hot',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    website: 'https://cursor.com',
    github_repo: 'getcursor/cursor',
    category: 'Developer Tools',
    description: 'AI-first code editor built for fast software development.',
    pricing: 'freemium',
    launched: 2023,
    trendScore: 96,
    weeklyGrowth: 12.8,
    monthlyVisits: 12300000,
    tags: ['ide', 'coding', 'ai-assistant'],
    status: 'hot',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    website: 'https://www.perplexity.ai',
    github_repo: 'ppl-ai/model-card',
    category: 'AI Writing',
    description: 'Answer engine combining web search with AI-generated responses.',
    pricing: 'freemium',
    launched: 2022,
    trendScore: 94,
    weeklyGrowth: 10.1,
    monthlyVisits: 98000000,
    tags: ['search', 'research', 'ai-assistant'],
    status: 'hot',
  },
  {
    id: 'clerk',
    name: 'Clerk',
    website: 'https://clerk.com',
    category: 'Developer Tools',
    description: 'Authentication and user management infrastructure for web apps.',
    pricing: 'freemium',
    launched: 2021,
    trendScore: 87,
    weeklyGrowth: 6.8,
    monthlyVisits: 3600000,
    tags: ['auth', 'security', 'sdk'],
    status: 'rising',
  },
  {
    id: 'loom',
    name: 'Loom',
    website: 'https://www.loom.com',
    category: 'Productivity',
    description: 'Async video messaging tool for work communication.',
    pricing: 'freemium',
    launched: 2016,
    trendScore: 80,
    weeklyGrowth: 2.4,
    monthlyVisits: 25000000,
    tags: ['video', 'communication', 'async'],
    status: 'stable',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    website: 'https://airtable.com',
    category: 'Productivity',
    description: 'Flexible database and app platform for operations and workflows.',
    pricing: 'freemium',
    launched: 2013,
    trendScore: 78,
    weeklyGrowth: 1.3,
    monthlyVisits: 19000000,
    tags: ['database', 'no-code', 'workflows'],
    status: 'stable',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    website: 'https://webflow.com',
    category: 'Design',
    description: 'Visual web design and CMS platform without heavy coding.',
    pricing: 'freemium',
    launched: 2013,
    trendScore: 85,
    weeklyGrowth: 4.1,
    monthlyVisits: 19000000,
    tags: ['website-builder', 'cms', 'no-code'],
    status: 'rising',
  },
  {
    id: 'framer',
    name: 'Framer',
    website: 'https://www.framer.com',
    category: 'Design',
    description: 'Interactive website builder focused on modern design teams.',
    pricing: 'freemium',
    launched: 2014,
    trendScore: 86,
    weeklyGrowth: 5.2,
    monthlyVisits: 6200000,
    tags: ['website-builder', 'design', 'prototyping'],
    status: 'rising',
  },
  {
    id: 'superhuman',
    name: 'Superhuman',
    website: 'https://superhuman.com',
    category: 'Productivity',
    description: 'Premium email client optimized for speed and productivity.',
    pricing: 'paid',
    launched: 2019,
    trendScore: 74,
    weeklyGrowth: 1.1,
    monthlyVisits: 1200000,
    tags: ['email', 'workflow', 'inbox'],
    status: 'stable',
  },
  {
    id: 'arc-browser',
    name: 'Arc',
    website: 'https://arc.net',
    category: 'Productivity',
    description: 'Modern browser designed for focused and organized web work.',
    pricing: 'free',
    launched: 2022,
    trendScore: 82,
    weeklyGrowth: 3.0,
    monthlyVisits: 3100000,
    tags: ['browser', 'workflow', 'tabs'],
    status: 'stable',
  },
  {
    id: 'raycast',
    name: 'Raycast',
    website: 'https://www.raycast.com',
    category: 'Productivity',
    description: 'Keyboard-first launcher and automation hub for professionals.',
    pricing: 'freemium',
    launched: 2020,
    trendScore: 83,
    weeklyGrowth: 3.8,
    monthlyVisits: 2600000,
    tags: ['launcher', 'automation', 'developer'],
    status: 'rising',
  },
  {
    id: 'cron-calendar',
    name: 'Cron',
    website: 'https://cron.com',
    category: 'Productivity',
    description: 'Fast calendar experience integrated with modern team workflows.',
    pricing: 'free',
    launched: 2021,
    trendScore: 69,
    weeklyGrowth: -0.6,
    monthlyVisits: 520000,
    tags: ['calendar', 'scheduling', 'productivity'],
    status: 'declining',
  },
  {
    id: 'cal-com',
    name: 'Cal.com',
    website: 'https://cal.com',
    category: 'Productivity',
    description: 'Open scheduling infrastructure for teams and products.',
    pricing: 'freemium',
    launched: 2021,
    trendScore: 81,
    weeklyGrowth: 2.7,
    monthlyVisits: 2800000,
    tags: ['scheduling', 'open-source', 'meetings'],
    status: 'stable',
  },
  {
    id: 'resend',
    name: 'Resend',
    website: 'https://resend.com',
    category: 'Developer Tools',
    description: 'Developer-focused email API with reliable delivery tools.',
    pricing: 'freemium',
    launched: 2023,
    trendScore: 89,
    weeklyGrowth: 7.7,
    monthlyVisits: 2400000,
    tags: ['email', 'api', 'transactional'],
    status: 'rising',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    website: 'https://www.anthropic.com',
    category: 'AI Writing',
    description: 'AI research and products including the Claude model family.',
    pricing: 'paid',
    launched: 2021,
    trendScore: 95,
    weeklyGrowth: 9.5,
    monthlyVisits: 43000000,
    tags: ['llm', 'safety', 'api'],
    status: 'hot',
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    website: 'https://www.grammarly.com',
    category: 'AI Writing',
    description: 'Writing assistant for grammar, clarity, and tone improvements.',
    pricing: 'freemium',
    launched: 2009,
    trendScore: 77,
    weeklyGrowth: 0.9,
    monthlyVisits: 62000000,
    tags: ['writing', 'editing', 'assistant'],
    status: 'stable',
  },
  {
    id: 'jasper',
    name: 'Jasper',
    website: 'https://www.jasper.ai',
    category: 'Marketing',
    description: 'AI marketing platform for campaign and copy generation.',
    pricing: 'paid',
    launched: 2021,
    trendScore: 71,
    weeklyGrowth: -1.1,
    monthlyVisits: 2600000,
    tags: ['copywriting', 'campaigns', 'brand'],
    status: 'declining',
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    website: 'https://www.copy.ai',
    category: 'Marketing',
    description: 'AI platform for automated content and sales messaging.',
    pricing: 'freemium',
    launched: 2020,
    trendScore: 73,
    weeklyGrowth: 1.5,
    monthlyVisits: 3300000,
    tags: ['copywriting', 'sales', 'automation'],
    status: 'stable',
  },
  {
    id: 'canva',
    name: 'Canva',
    website: 'https://www.canva.com',
    category: 'Design',
    description: 'Visual design platform for social posts, docs, and presentations.',
    pricing: 'freemium',
    launched: 2013,
    trendScore: 88,
    weeklyGrowth: 3.7,
    monthlyVisits: 290000000,
    tags: ['design', 'templates', 'social-media'],
    status: 'rising',
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    website: 'https://www.adobe.com/products/firefly.html',
    category: 'AI Image',
    description: 'Generative AI tools for image creation and editing workflows.',
    pricing: 'freemium',
    launched: 2023,
    trendScore: 86,
    weeklyGrowth: 4.9,
    monthlyVisits: 12500000,
    tags: ['generative-ai', 'image-editing', 'creative'],
    status: 'rising',
  },
  {
    id: 'dall-e',
    name: 'DALL-E',
    website: 'https://openai.com/dall-e',
    category: 'AI Image',
    description: 'Text-to-image model for generating visuals from prompts.',
    pricing: 'paid',
    launched: 2021,
    trendScore: 83,
    weeklyGrowth: 2.2,
    monthlyVisits: 7400000,
    tags: ['text-to-image', 'creative', 'openai'],
    status: 'stable',
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    website: 'https://stability.ai',
    category: 'AI Image',
    description: 'Open model ecosystem for image generation and customization.',
    pricing: 'free',
    launched: 2022,
    trendScore: 72,
    weeklyGrowth: -1.5,
    monthlyVisits: 5400000,
    tags: ['open-source', 'image-generation', 'models'],
    status: 'declining',
  },
  {
    id: 'runway',
    name: 'Runway',
    website: 'https://runwayml.com',
    category: 'Design',
    description: 'Creative suite for AI video and multimedia generation.',
    pricing: 'freemium',
    launched: 2018,
    trendScore: 87,
    weeklyGrowth: 5.5,
    monthlyVisits: 9800000,
    tags: ['video', 'generative-ai', 'creative'],
    status: 'rising',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    website: 'https://www.hubspot.com',
    category: 'Marketing',
    description: 'CRM and marketing automation platform for growth teams.',
    pricing: 'freemium',
    launched: 2006,
    trendScore: 82,
    weeklyGrowth: 2.0,
    monthlyVisits: 37000000,
    tags: ['crm', 'automation', 'inbound'],
    status: 'stable',
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    website: 'https://mailchimp.com',
    category: 'Marketing',
    description: 'Email marketing and audience management platform.',
    pricing: 'freemium',
    launched: 2001,
    trendScore: 68,
    weeklyGrowth: -0.9,
    monthlyVisits: 26000000,
    tags: ['email-marketing', 'campaigns', 'audience'],
    status: 'declining',
  },
  {
    id: 'semrush',
    name: 'Semrush',
    website: 'https://www.semrush.com',
    category: 'Marketing',
    description: 'SEO and digital marketing analytics toolkit.',
    pricing: 'paid',
    launched: 2008,
    trendScore: 76,
    weeklyGrowth: 1.0,
    monthlyVisits: 42000000,
    tags: ['seo', 'keywords', 'competitive-intel'],
    status: 'stable',
  },
  {
    id: 'ahrefs',
    name: 'Ahrefs',
    website: 'https://ahrefs.com',
    category: 'Marketing',
    description: 'SEO platform for backlink analysis and content research.',
    pricing: 'paid',
    launched: 2011,
    trendScore: 75,
    weeklyGrowth: 0.8,
    monthlyVisits: 18000000,
    tags: ['seo', 'backlinks', 'content'],
    status: 'stable',
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    website: 'https://mixpanel.com',
    category: 'Analytics',
    description: 'Product analytics platform focused on user behavior insights.',
    pricing: 'freemium',
    launched: 2009,
    trendScore: 79,
    weeklyGrowth: 1.9,
    monthlyVisits: 4200000,
    tags: ['product-analytics', 'events', 'retention'],
    status: 'stable',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    website: 'https://amplitude.com',
    category: 'Analytics',
    description: 'Digital analytics suite for product and growth teams.',
    pricing: 'freemium',
    launched: 2012,
    trendScore: 81,
    weeklyGrowth: 2.2,
    monthlyVisits: 6900000,
    tags: ['analytics', 'product', 'experimentation'],
    status: 'stable',
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    website: 'https://analytics.google.com',
    category: 'Analytics',
    description: 'Web and app analytics platform by Google.',
    pricing: 'free',
    launched: 2005,
    trendScore: 78,
    weeklyGrowth: 0.4,
    monthlyVisits: 280000000,
    tags: ['web-analytics', 'traffic', 'google'],
    status: 'stable',
  },
  {
    id: 'hotjar',
    name: 'Hotjar',
    website: 'https://www.hotjar.com',
    category: 'Analytics',
    description: 'Behavior analytics with heatmaps, recordings, and feedback tools.',
    pricing: 'freemium',
    launched: 2014,
    trendScore: 74,
    weeklyGrowth: 0.7,
    monthlyVisits: 7200000,
    tags: ['heatmaps', 'ux', 'feedback'],
    status: 'stable',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    website: 'https://www.intercom.com',
    category: 'Customer Support',
    description: 'Customer messaging and AI support platform for businesses.',
    pricing: 'paid',
    launched: 2011,
    trendScore: 83,
    weeklyGrowth: 2.9,
    monthlyVisits: 11000000,
    tags: ['support', 'chat', 'customer-success'],
    status: 'rising',
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    website: 'https://www.zendesk.com',
    category: 'Customer Support',
    description: 'Ticketing and omnichannel support suite for service teams.',
    pricing: 'paid',
    launched: 2007,
    trendScore: 73,
    weeklyGrowth: 0.3,
    monthlyVisits: 36000000,
    tags: ['ticketing', 'support', 'helpdesk'],
    status: 'stable',
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    website: 'https://freshdesk.com',
    category: 'Customer Support',
    description: 'Helpdesk platform for support operations and automations.',
    pricing: 'freemium',
    launched: 2010,
    trendScore: 70,
    weeklyGrowth: -0.4,
    monthlyVisits: 9800000,
    tags: ['helpdesk', 'ticketing', 'support'],
    status: 'declining',
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    website: 'https://www.gorgias.com',
    category: 'Customer Support',
    description: 'Ecommerce-focused customer support platform with automation.',
    pricing: 'paid',
    launched: 2015,
    trendScore: 77,
    weeklyGrowth: 1.7,
    monthlyVisits: 1700000,
    tags: ['ecommerce', 'support', 'automation'],
    status: 'stable',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    website: 'https://stripe.com',
    category: 'Finance',
    description: 'Online payments and financial infrastructure for internet businesses.',
    pricing: 'paid',
    launched: 2010,
    trendScore: 89,
    weeklyGrowth: 3.6,
    monthlyVisits: 59000000,
    tags: ['payments', 'api', 'billing'],
    status: 'rising',
  },
  {
    id: 'xero',
    name: 'Xero',
    website: 'https://www.xero.com',
    category: 'Finance',
    description: 'Cloud accounting software for small and medium businesses.',
    pricing: 'paid',
    launched: 2006,
    trendScore: 72,
    weeklyGrowth: 0.6,
    monthlyVisits: 7600000,
    tags: ['accounting', 'bookkeeping', 'finance'],
    status: 'stable',
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    website: 'https://quickbooks.intuit.com',
    category: 'Finance',
    description: 'Accounting and invoicing platform for business finances.',
    pricing: 'paid',
    launched: 1998,
    trendScore: 71,
    weeklyGrowth: 0.2,
    monthlyVisits: 41000000,
    tags: ['accounting', 'invoicing', 'tax'],
    status: 'stable',
  },
  {
    id: 'brex',
    name: 'Brex',
    website: 'https://www.brex.com',
    category: 'Finance',
    description: 'Corporate cards and spend management for modern companies.',
    pricing: 'paid',
    launched: 2017,
    trendScore: 76,
    weeklyGrowth: 1.4,
    monthlyVisits: 2100000,
    tags: ['expense-management', 'cards', 'fintech'],
    status: 'stable',
  },
  {
    id: 'ramp',
    name: 'Ramp',
    website: 'https://ramp.com',
    category: 'Finance',
    description: 'Finance automation and expense platform for growing teams.',
    pricing: 'free',
    launched: 2020,
    trendScore: 85,
    weeklyGrowth: 4.6,
    monthlyVisits: 2300000,
    tags: ['expenses', 'automation', 'cards'],
    status: 'rising',
  },
  {
    id: 'gusto',
    name: 'Gusto',
    website: 'https://gusto.com',
    category: 'HR',
    description: 'Payroll, benefits, and HR platform for small businesses.',
    pricing: 'paid',
    launched: 2012,
    trendScore: 80,
    weeklyGrowth: 2.1,
    monthlyVisits: 11500000,
    tags: ['payroll', 'benefits', 'hr'],
    status: 'stable',
  },
  {
    id: 'rippling',
    name: 'Rippling',
    website: 'https://www.rippling.com',
    category: 'HR',
    description: 'Unified HR, IT, and payroll system for companies.',
    pricing: 'paid',
    launched: 2016,
    trendScore: 86,
    weeklyGrowth: 4.0,
    monthlyVisits: 4200000,
    tags: ['hris', 'payroll', 'it-management'],
    status: 'rising',
  },
  {
    id: 'deel',
    name: 'Deel',
    website: 'https://www.deel.com',
    category: 'HR',
    description: 'Global hiring, payroll, and compliance platform.',
    pricing: 'paid',
    launched: 2019,
    trendScore: 84,
    weeklyGrowth: 3.4,
    monthlyVisits: 9200000,
    tags: ['global-payroll', 'compliance', 'contracts'],
    status: 'rising',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    website: 'https://www.greenhouse.com',
    category: 'HR',
    description: 'Recruiting software for structured hiring processes.',
    pricing: 'paid',
    launched: 2012,
    trendScore: 74,
    weeklyGrowth: 0.8,
    monthlyVisits: 3400000,
    tags: ['ats', 'recruiting', 'hiring'],
    status: 'stable',
  },
  {
    id: 'lever',
    name: 'Lever',
    website: 'https://www.lever.co',
    category: 'HR',
    description: 'Talent acquisition suite for sourcing and hiring teams.',
    pricing: 'paid',
    launched: 2013,
    trendScore: 69,
    weeklyGrowth: -0.7,
    monthlyVisits: 1700000,
    tags: ['ats', 'talent', 'recruitment'],
    status: 'declining',
  },
  {
    id: 'monday',
    name: 'Monday.com',
    website: 'https://monday.com',
    category: 'Productivity',
    description: 'Work management platform for projects and operations.',
    pricing: 'freemium',
    launched: 2014,
    trendScore: 79,
    weeklyGrowth: 1.6,
    monthlyVisits: 27000000,
    tags: ['work-management', 'projects', 'collaboration'],
    status: 'stable',
  },
  {
    id: 'asana',
    name: 'Asana',
    website: 'https://asana.com',
    category: 'Productivity',
    description: 'Task and project management software for team coordination.',
    pricing: 'freemium',
    launched: 2011,
    trendScore: 76,
    weeklyGrowth: 0.8,
    monthlyVisits: 38000000,
    tags: ['tasks', 'projects', 'teams'],
    status: 'stable',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    website: 'https://clickup.com',
    category: 'Productivity',
    description: 'Productivity suite combining docs, tasks, and goals in one place.',
    pricing: 'freemium',
    launched: 2017,
    trendScore: 82,
    weeklyGrowth: 2.5,
    monthlyVisits: 30000000,
    tags: ['productivity', 'tasks', 'docs'],
    status: 'rising',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    website: 'https://zapier.com',
    category: 'Developer Tools',
    description: 'Automation platform connecting apps and business workflows.',
    pricing: 'freemium',
    launched: 2012,
    trendScore: 81,
    weeklyGrowth: 1.7,
    monthlyVisits: 28000000,
    tags: ['automation', 'integrations', 'no-code'],
    status: 'stable',
  },
  {
    id: 'make',
    name: 'Make',
    website: 'https://www.make.com',
    category: 'Developer Tools',
    description: 'Visual automation builder for multi-step integrations.',
    pricing: 'freemium',
    launched: 2016,
    trendScore: 80,
    weeklyGrowth: 2.1,
    monthlyVisits: 7300000,
    tags: ['automation', 'integrations', 'workflow'],
    status: 'stable',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    website: 'https://posthog.com',
    category: 'Analytics',
    description: 'Open-source product analytics and feature flag platform.',
    pricing: 'freemium',
    launched: 2020,
    trendScore: 88,
    weeklyGrowth: 6.3,
    monthlyVisits: 2600000,
    tags: ['analytics', 'feature-flags', 'open-source'],
    status: 'rising',
  },
];
